language: java

matrix:
  include:
    - os: linux
      jdk: openjdk7
    - os: linux
      jdk: openjdk8
    - os: linux
      jdk: openjdk11
    - os: linux
      jdk: openjdk12

before_install:
# https://github.com/travis-ci/travis-ci/issues/8408
  - unset _JAVA_OPTIONS

before_script: true
install: true

script:
  - mvn -V -P+run-its clean verify

cache:
  directories:
  - "$HOME/.cache"
  - "$HOME/.m2"
